### ISSUE TITLE
As a user i want to have a 2d grid that can be played on. So that i have an area to play in.

### ISSUE THREAD

**Issue by Wilmer-Chas** [RubinAtChas/boilerroom5#4]

**Comment by RubinAtChas** [comment]
Creating a 2D grid is the first thing to do. So that we have an overview of what functions to insert.

Creating 2D grid. Using class, inside the class is:
Grid that is a 2D Array
15x15.
Set a value of the tiles. Ex: Water/Empty.
Include coordinates to simplify placing and or shooting the tiles.
Create a function that changes the status of the tile ex: (Hit, empty, missed, ship.)

**Comment by RubinAtChas** [comment]
Tasks för user storyn
Designa datastrukturen för 2D-rutnätet

Skapa en datastruktur (t.ex. en 2D-array eller vektor) för att representera spelbrädet.
Definiera storleken på rutnätet (t.ex. 15x15 för ett standard Battleship-spel).
Implementera en funktion för att initialisera rutnätet

Skriv en funktion som skapar rutnätet och sätter alla rutor till ett initialt värde (t.ex. 'vatten' eller 'tomt').
Skapa en funktion för att skriva ut rutnätet till konsolen

Utveckla en funktion som kan visa rutnätet i konsolen på ett sätt som är läsbart för spelaren.
Inkludera koordinater för att underlätta placering och skjutande på rutor.
Implementera en funktion för att uppdatera en rutans status

Lägg till en funktion som kan ändra en ruts tillstånd (t.ex. träffad, missad, eller skepp) baserat på spelarens handlingar.
Hantera olika tillstånd för varje ruta (t.ex. skepp, vatten, träffat skepp).
